
import * as XLSX from 'xlsx';
import { User, Student, AttendanceRecord, DiaryEntry, MonthlyReportData } from '../types';

export const ExcelService = {
  // Utility to create and save a workbook from an Array of Arrays
  createAndSave: (filename: string, sheetName: string, data: any[][]) => {
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(data);
    XLSX.utils.book_append_sheet(wb, ws, sheetName);
    XLSX.writeFile(wb, `${filename}.xlsx`);
  },

  generateAdmissionExcel: (student: Student, user: User) => {
    const data = [
      ['PRAVAH STUDENT ADMISSION FORM'],
      ['Center Name', user.centerName],
      ['Center ID', user.centerId],
      ['Generated By', user.name],
      ['Date', new Date().toLocaleDateString()],
      [],
      ['STUDENT DETAILS'],
      ['Student ID', student.id],
      ['Full Name', student.name],
      ['Gender', student.gender],
      ['Date of Birth', student.dob],
      ['Age', student.age],
      ['Class', student.classLevel],
      ['School Name', student.schoolName],
      ['Registration No', student.registrationNumber || '-'],
      [],
      ['GUARDIAN DETAILS'],
      ['Guardian Name', student.parentName],
      ['Occupation', student.parentOccupation || '-'],
      ['Contact', student.contact],
      ['Aadhaar', student.aadhaar || '-'],
      [],
      ['OFFICE USE'],
      ['Admission Date', student.admissionDate],
      ['Admission File', student.admissionFormFile || 'Not Uploaded']
    ];

    ExcelService.createAndSave(`Admission_${student.id}`, 'Student Info', data);
  },

  generateAttendanceExcel: (students: Student[], presentIds: Set<string>, mode: string, user?: User) => {
    const dateStr = new Date().toISOString().split('T')[0];
    
    // Header Section
    const header = [
      ['PRAVAH ATTENDANCE REPORT'],
      ['Center', user?.centerName || 'Unknown'],
      ['Date', dateStr],
      ['Mode', mode],
      ['Total Students', students.length],
      ['Present', presentIds.size],
      ['Absent', students.length - presentIds.size],
      [] // Empty row
    ];

    // Table Header
    const tableHeader = ['Sr No', 'Student Name', 'Student ID', 'Class', 'Status'];

    // Table Data
    const tableRows = students.map((s, i) => [
      i + 1,
      s.name,
      s.id,
      s.classLevel,
      presentIds.has(s.id) ? 'Present' : 'Absent'
    ]);

    const finalData = [...header, tableHeader, ...tableRows];
    ExcelService.createAndSave(`Attendance_${dateStr}`, 'Attendance Log', finalData);
  },

  generateDiaryExcel: (entry: DiaryEntry, user: User) => {
    const data = [
      ['PRAVAH UPAY DIARY LOG'],
      ['Center', user.centerName],
      ['Date', entry.date],
      ['Recorded By', user.name],
      [],
      ['CENTER ACTIVITIES'],
      ['Timing', `${entry.inTime} - ${entry.outTime}`],
      ['Students Present', entry.studentCount],
      ['Thought of the Day', entry.thought],
      [],
      ['VOLUNTEER LOGS'],
      ['Volunteer ID', 'Volunteer Name', 'Status', 'Class Handled', 'Subject', 'Topic']
    ];

    const volRows = entry.volunteers.map(v => [
      v.volunteerId,
      v.name,
      v.status,
      v.classHandled,
      v.subject,
      v.topic
    ]);

    const finalData = [...data, ...volRows];
    ExcelService.createAndSave(`Diary_${entry.date}`, 'Diary Entry', finalData);
  },

  generateHistoryExcel: (historyItems: any[], user: User) => {
      const header = [
          ['PRAVAH HISTORY EXPORT'],
          ['Center', user.centerName],
          ['Export Date', new Date().toLocaleDateString()],
          []
      ];

      const tableHeader = ['Date', 'Type', 'Summary', 'Raw Data ID', 'Additional Info'];
      
      const rows = historyItems.map(item => [
          item.date,
          item.type,
          item.details,
          item.id,
          // Extract some extra info based on type
          item.type === 'Attendance' ? `Mode: ${item.data.mode}, Total: ${item.data.totalStudents}` :
          item.type === 'Admission' ? `Class: ${item.data.classLevel}, Parent: ${item.data.parentName}` :
          item.type === 'Diary' ? `Vols: ${item.data.volunteers?.length}` : ''
      ]);

      const finalData = [...header, tableHeader, ...rows];
      ExcelService.createAndSave(`Pravah_History_Export`, 'History', finalData);
  },

  generateMonthlyExcel: (report: MonthlyReportData, user: User) => {
      const header = [
          ['PRAVAH MONTHLY ATTENDANCE REPORT'],
          ['Center', user.centerName],
          ['Month/Year', `${report.month} ${report.year}`],
          ['Class', report.className],
          ['Working Days', report.workingDays],
          ['Avg Attendance', `${Math.round(report.averageAttendance)}%`],
          []
      ];

      const tableHeader = ['Sr No', 'Student Name', 'ID', 'Days Present', 'Attendance %'];
      
      const rows = report.studentStats.map((s, i) => [
          i + 1,
          s.name,
          s.studentId,
          s.presentDays,
          Math.round(s.percentage) + '%'
      ]);

      const finalData = [...header, tableHeader, ...rows];
      ExcelService.createAndSave(`Attendance_${report.month}_${report.year}`, 'Monthly Summary', finalData);
  }
};